import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { prisma } from "@/lib/db";
import { Post } from "@prisma/client";

interface Props {
  post: Post[];
}

const Home: NextPage<Props> = ({ post }) => {

  let data = post[0].content;
  console.log('post', data?.rendered)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="border-2 p-10">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>

      </div>
      {data?.rendered &&  <div dangerouslySetInnerHTML={{ __html: data?.rendered }} />}
     
     
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  let post: Post[] = [];
  try {
    post = await prisma.post.findMany();
  } catch (error) {
    console.log(error);
  }
  return {
    props: { post },
  };
};

export default Home;
